server:
  port: 8008
  tomcat:
    uri-encoding: utf-8
  servlet:
    jsp:
      init-parameters:
        development: true

mybatis:
  config-location:  classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shape_code?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://47.98.166.74:13306/shape_code?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    driverClassName: com.mysql.jdbc.Driver
#    username: dev
#    password: Joyuai2020.
  jpa:
    show-sql: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.hainiu.cat.dao.model

#elasticsearch:
#  hostname: localhost   #elasticsearch服务器地址
#  port: 9200                  #elasticsearch服务器端口